zabbix/datasource.js
This method now uses the same request doZabbixAPIRequest without code
dublication. Please check on your installation cause I have only one
metric per graph
I thinl idea is clear to remove code dublication with auth, and do all requests thru doZabbixAPIRequest
=> Rewritten ptototype.query method

zabbix/datasource.js
As seen in alexanderzobnin/grafana-zabbix#66, repeat panel and row does not work with Zabbix datasource.
This comes from Host and items filters which does not support it.
I think I found a way to enable them. Not sure it'll cover all cases, but at least my dashboard works now :)
=> Enable scoped variables in Zabbix datasource

src/datasource-zabbix/add-metric-function.directive.js, src/datasource-zabbix/partials/query.editor.html, src/datasource-zabbix/query.controller.js
Just merged a breaking change to master (sorry to do this this late in beta phase), but want to update the query editor styles now before more data sources are made, so the breaking change is less painful now. 
this PR updates the zabbix data source query editor. Had to move the menu actions to the actual query editor as the query-row-component that controls the menu and the other actions does not support custom panel actions yet.
=> feat(query editor): Updated query editor to use new forms styles/markup and outer component

src/datasource-zabbix/zabbixAPI.service.js
MACROs in trigger descriptions of the trigger panel are not expanded currently, this path to enable that
=> enable expanding MACRO in trigger descriptions

src/datasource-zabbix/timeseries.js
Patch to fix misleading "data points outside time range" alert message on a graph using aggregate function (say median(10m)) if metric has no data in a selected time range.
groupBy_perf function in datasource-zabbix/timeseries.js do not properly handle empty datapoints[] case inserting bogus [undefined, 0] sample with last grouped_series.push([frame_value, frame_ts]) call.
=> Fix "data points outside time range" when there is no datapoints and aggregate function is used

src/datasource-zabbix/zabbixAPI.service.js
Solves issue #352
However, I've only tested it on Zabbix 2.0.6.
According to it's docs `output: 'extend'` should not break anything for other versions, but I might be wrong.
=> Request extended output for applications from service

src/datasource-zabbix/partials/config.html
Because it was empty.
Moreover, it requires not usual url, but url to Zabbix Api file (api_jsonrpc.php), so It it will be easier to connect with this placeholder.
Before:
After:
=> Add placeholder for suggest-url

src/datasource-zabbix/zabbix/connectors/sql/sqlConnector.js
This fixes https://github.com/alexanderzobnin/grafana-zabbix/issues/603.
After the fix, the produced SQL query looks like the following:
```
SELECT itemid AS metric, clock DIV 7200 * 7200 AS time_sec, SUM(num*value_avg) AS value FROM trends_uint WHERE itemid IN (282744, 282835) AND clock > 1531999580 AND clock < 1532604380 GROUP BY clock DIV 7200 * 7200, metric ORDER BY time_sec ASC
```
The calculated sum is correct since it sums the actual data values and not the one-hour trend period averages.
=> consolidateBy(sum) must calculate sums inside the one-hour trend period

.codecov.yml, docs/mkdocs.yml, docs/sources/configuration/direct_db_datasource.md, docs/sources/configuration/index.md, docs/sources/configuration/provisioning.md, docs/sources/img/configuration-influxdb_ds_config.png, docs/sources/reference/direct-db-connection.md, src/datasource-zabbix/config.controller.js, src/datasource-zabbix/datasource.js, src/datasource-zabbix/partials/config.html, src/datasource-zabbix/specs/datasource.spec.js, src/datasource-zabbix/specs/dbConnector.test.js, src/datasource-zabbix/specs/influxdbConnector.test.js, src/datasource-zabbix/utils.js, src/datasource-zabbix/zabbix/connectors/dbConnector.js, src/datasource-zabbix/zabbix/connectors/influxdb/influxdbConnector.js, src/datasource-zabbix/zabbix/connectors/sql/sqlConnector.js, src/datasource-zabbix/zabbix/zabbix.js, src/test-setup/jest-setup.js
This PR closes #640 and adds support for InfluxDB as Direct DB Connection datasource along with MySQL and Postgres.
=> Support InfluxDB as a history db

src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.js, src/panel-triggers/components/Problems/ProblemDetails.tsx, src/panel-triggers/components/Problems/ProblemStatusBar.tsx, src/panel-triggers/components/Problems/Problems.tsx, src/panel-triggers/triggers_panel_ctrl.js, src/panel-triggers/types.ts
This PR fixes #712 and #720
The performance problems were caused by a large amount of data fetched by `alert.get` API method. Since the only usage of that data is showing problem alert message, the most gentle solution is to fetch this data only for the particular problem on demand (when user opens details of the problem).
=> Fix problems panel performance and memory issues caused by alert.get method

go.mod, go.sum, pkg/cache.go, pkg/zabbix_api.go
Issue https://github.com/alexanderzobnin/grafana-zabbix/issues/802
Implemented caching for API Queries by using go-cache as mentioned in the issue. Converted the DatasourceRequest to a hash string and stored the response against it. The expiration time and cleanup time are given as 10 minutes.
=> Backend: caching the Zabbix API Queries

src/datasource-zabbix/dataProcessor.js
Like the other aggregation functions, the datapoints need to be sorted in
time before calling groupBy_perf().
Closes #862
=> Fix percentile() function, closes #862

src/panel-triggers/components/AlertList/AlertCard.tsx, src/panel-triggers/components/Problems/Problems.tsx
This PR closes #857.
As described in the issue #857 if a problem contains a message without the acknowledgment, then the severity color is shown as acknowleged in both views: table and list.
Zabbix [event object](https://www.zabbix.com/documentation/current/manual/api/reference/event/get) has property "acknowledged" which is 1 if the event has been acknowledged. I've used this property instead of "acknowledges" object, because acknowledges will contain the message attached to the event even if the event is not acknowleged.
=> fix not acknowledged problem color with a message

src/panel-triggers/components/AlertList/AlertCard.tsx, src/panel-triggers/components/Problems/Problems.tsx, src/panel-triggers/triggers_panel_ctrl.js, src/panel-triggers/types.ts
This PR closes #870.
- Added a new property "severity" to the ZBXEvent.
- Panel problems for both layouts: show severity from the lastEvent.severity if it exists.
- Create triggerList based on lastEvent.severity if it exists.
Not sure about the code style. It works in my production, but I'm not an expert in typescript/javascript.
=> fix event severity change

src/panel-triggers/triggers_panel_ctrl.js
* Add scopedVars parameters to replaceTemplateVars function call in getTriggers function.
[\[Bug\] Wrong variable scope inside repeated rows #912](https://github.com/alexanderzobnin/grafana-zabbix/issues/912)
=> [Bug] Wrong variable scope inside repeated rows

docs/sources/configuration/index.md
The original linked file in section `Direct DB Connection` is missing,
> Read how to configure SQL data source in Grafana.
change it to [direct_db_datasource](https://github.com/alexanderzobnin/grafana-zabbix/blob/docs/docs/sources/configuration/direct_db_datasource.md)
Fixes #901
=> [Doc] change link in index.md

src/datasource-zabbix/utils.js, src/datasource-zabbix/zabbix/zabbix.js
Fix to issue #190 
Currently macros in trigger URL field don't get expanded.
This fix checks trigger URL against macros and expands all found macros.
=> Expand macros in trigger URL fields

docs/sources/configuration/index.md, docs/sources/configuration/provisioning.md, pkg/datasource/response_handler.go, pkg/datasource/zabbix.go, pkg/timeseries/models.go, pkg/timeseries/timeseries.go, src/datasource-zabbix/components/ConfigEditor.tsx, src/datasource-zabbix/datasource.ts, src/datasource-zabbix/partials/query.editor.html, src/datasource-zabbix/problemsHandler.ts, src/datasource-zabbix/query.controller.ts, src/datasource-zabbix/responseHandler.ts, src/datasource-zabbix/timeseries.ts, src/datasource-zabbix/types.ts, src/datasource-zabbix/utils.ts, src/datasource-zabbix/zabbix/connectors/dbConnector.js, src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts, src/datasource-zabbix/zabbix/zabbix.ts
This PR closes #1082 by migrating response to the new Data Frames format.
=> Use Data frames response format

pkg/datasource/zabbix.go, src/datasource-zabbix/partials/query.editor.html, src/datasource-zabbix/query.controller.ts, src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts, src/datasource-zabbix/zabbix/types.ts, src/datasource-zabbix/zabbix/zabbix.ts
This PR fixes #1188 by simply ignoring application filter.
This is only compatibility fix. Tags support will be added in the 4.2 release.
=> Fix compatibility with Zabbix 5.4 (skip applications filter)

pkg/timeseries/timeseries.go
Fixes #1310
This is required to properly aggregate by full interval.
See:
- Current behavior: https://play.golang.org/p/c6J3EdFp8KC
- Fixed behavior after this PR: https://play.golang.org/p/lustHMtW7ZD
=> Use time.Truncate instead of time.Round in GetTimeFrame

src/datasource-zabbix/problemsHandler.ts
=> Fixes incorrect problem name when PROBLEM event generation mode set to multiple

devenv/README.md, devenv/zabbix62/bootstrap/Dockerfile, devenv/zabbix62/bootstrap/bootstrap_config.py, devenv/zabbix62/bootstrap/zbx_export_hosts.xml, devenv/zabbix62/docker-compose.yml, pkg/zabbix/methods.go, src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts
This PR fixes #1470 by adding `groupid` param explicitly to host groups queries.
=> Fix hostgroup.get in Zabbix 6.2

go.mod, go.sum, pkg/zabbix/methods.go, pkg/zabbix/utils.go, pkg/zabbix/utils_test.go
I changed the returned regexp of `parseFilter()` to regexp2. I kept all other uses `regexp` since there's no need for a switch and `regexp2` seems to be unnecessary complex to use for something like `FindStringSubmatch()`.
I haven't run any tests on a real grafana instance, I'll try that later. But I extended the tests and they passed.
If there's anything I could/should change, just let me know! :)
This PR should fix #1264
=> Switch to regexp2 for parseFilter()

Makefile
Both architectures supported by Go on FreeBSD.
Slightly simplified Makefile to avoid repeating same build commands for every variation of `GOOS`/`GOARCH`.
Fixes #1301, fixes #1402, fixes #1237, and fixes #1203.
=> Build for FreeBSD amd64 & arm64

CHANGELOG.md, pkg/datasource/zabbix_test.go, pkg/settings/models.go, pkg/settings/settings.go, pkg/zabbix/zabbix.go, pkg/zabbix/zabbix_test.go, pkg/zabbixapi/zabbix_api.go, src/datasource/components/ConfigEditor.tsx, src/datasource/types.ts
This PR adds API tokens authentication introduced in Zabbix 5.4.
Fixes #1513
=> Auth: Able to use API tokens for authentication

src/datasource/datasource.ts, src/datasource/specs/datasource.spec.ts, src/datasource/tracking.ts, src/panel-triggers/components/Problems/Problems.tsx
track executed queries so we can view some stats around the datasource
this includes but not limited to:
- how many queries are sent
- how often each query type is used
- etc.
Fixes [#72899](https://github.com/grafana/grafana/issues/72899)
=> track executed queries and panel clicks

src/datasource/components/FunctionEditor/FunctionEditorControls.tsx, src/datasource/query_help.md
Fixes #1700 by directing to new documentation at https://grafana.github.io/grafana-zabbix
=> Doc: Fix broken link in query editor and doc

src/datasource/tracking.ts
currently we track all query requests, this PR excludes requests on dashboard reload which improves performance.
=> Don't track query requests on dashboard reload

src/datasource/specs/dbConnector.test.ts, src/datasource/specs/timeseries.spec.ts, src/datasource/specs/utils.spec.ts, src/datasource/zabbix/connectors/zabbix_api/types.ts
=> Chore: Fix prettier issues in test files

src/datasource/components/ConfigEditor.tsx
after the configuration page updates the `Reset` button for the zabbix password stopped working.
this fixes that so the user can update the configured password.
=> fix reset bug in config page

src/datasource/components/ConfigEditor.tsx, src/datasource/zabbix/connectors/sql/sqlConnector.ts
fixes https://github.com/grafana/grafana-zabbix/issues/1764
the plugin-id for the postgres-datasource-plugin changed between 10.2.2 and 10.2.3:
- in 10.2.2: it is `postgres`
- in 10.2.3: it is `grafana-postgresql-datasource`
the PR changes the code so that we accept both possible ids.
=> handle changed postgres-plugin-id

docs/sources/configuration/_index.md, docs/sources/configuration/direct-db-datasource.md, docs/sources/guides/_index.md, docs/sources/guides/templating.md, docs/sources/reference/direct-db-connection.md
=> Docs: rename image paths

docs/sources/reference/functions.md, pkg/timeseries/moving_average.go, pkg/zabbixapi/zabbix_api.go
=> chore: fix some comments

CHANGELOG.md, devenv/zabbix70/bootstrap/Dockerfile, devenv/zabbix70/bootstrap/bootstrap_config.py, devenv/zabbix70/bootstrap/zbx_export_hosts.json, package.json, src/datasource/problemsHandler.ts, src/datasource/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts, src/datasource/zabbix/zabbix.ts
This PR adds support for version 7 of Zabbix by fixing the breaking changes. You can try this out by spinning up the zabbix07 devenv.
Fixes #1714
=> Add support for v7

src/datasource/zabbix/connectors/zabbix_api/zabbixAPIConnector.test.ts, src/datasource/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts
I messed up the version comparison. lte means less then or equal. In the `getProxies` function I was even used it wrongly as `name` is only supported in version 7 and above.
How to test:
spin up devenv70 and devenv62.
open explore with problems query.
Fixes #1837
=> Fix: Problems panel failing for versions before 7.0.0

src/plugin.json
This is required so that we can serve Zabbix on the plugin CDN
=> Add nested plugin paths to includes

src/styles/_panel-triggers.scss
- as part of https://github.com/grafana/grafana/pull/90224, i removed these SCSS styles from core grafana
- unfortunately the dashboard i was using to see which plugins were using which styles never flagged this plugin as using them 😭
- still need to dig into how and why these usages weren't shown
- copy these styles into the plugin where they can be controlled and adjusted at your leisure 😄 
thanks to @PedroRibas13 @mplm17 for raising this 🙇 
Fixes https://github.com/grafana/grafana-zabbix/issues/1868
=> Bug: Fix `AlertList` styling

devenv/dashboards/template_linux_server.json, devenv/dashboards/zabbix_datasource_features.json, devenv/zabbix70/docker-compose.yml, src/datasource/dashboards/template_linux_server.json, src/datasource/dashboards/zabbix_server_dashboard.json, src/datasource/dashboards/zabbix_system_status.json
This PR updates the example dashboards to the latest schema and migrates away from angular panels. It also tweaks the queries a bit so those are more meaningful.
Fixes #1639
=> Update example dashboards

pkg/datasource/datasource.go, pkg/datasource/functions.go, pkg/datasource/functions_test.go, pkg/datasource/response_handler.go, pkg/zabbix/type_converters.go, pkg/zabbix/utils.go, pkg/zabbix/zabbix.go, pkg/zabbix/zabbix_test.go, pkg/zabbixapi/zabbix_api.go, pkg/zabbixapi/zabbix_api_test.go
=> Add error source

Makefile
This is the recommended approach since Go 1.17
I was getting an error when running `make install`:
```
GO111MODULE=off go get -u golang.org/x/lint/golint
go: modules disabled by GO111MODULE=off; see 'go help modules'
```
=> Use `go install` to install golint

.changeset/gentle-bees-rescue.md, src/datasource/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts
This PR fixes 2 issues mentioned below.
Fixes #1943
Fixes #1946
[src/panel-triggers/components/Problems/Problems.tsx](https://github.com/grafana/grafana-zabbix/blob/0355f40fc22fc0e7cb82fced61a9487745c7e640/src/panel-triggers/components/Problems/Problems.tsx)
1. Go to `Zabbix data source features` dashboard
2. Open Problems panel
3. In the panel config enable host groups field
4. Host groups should show up in the table
1. Go to explore and select the zabbix ds
2. Select `Triggers` Query type
3. Add `Backend` as a group
4. Add `/.*/` as host
5. There should be 2 average triggers
=> Fix: host groups not showing in problems panel

.github/workflows/compatibility-50.yml, .github/workflows/compatibility-60.yml, .github/workflows/compatibility-70.yml, .github/workflows/compatibility-72.yml
The read value for id-token is not available. This PR fixes that.
=> Remove id-token permission for compatibility workflows

src/datasource/responseHandler.spec.ts, src/datasource/responseHandler.ts
Fixes #1982
With a refID of `test test`
Before
After
=> Forward refID to resultant dataframe

.changeset/stupid-coats-accept.md, src/datasource/zabbix/zabbix.ts
In order to reproduce this you need to create a Service and an SLO. The bug appears when an SLO is not set.
Fixes #1784
=> Fix: slaid is missing error
