grafana/grafana-zabbix

- zabbix/datasource.js
- zabbix/plugin.json
@alexanderzobnin with this fix,Grafana-Zabbix would work with Grafana-2.5.
> path fix & use dateMath instead of kbn

- zabbix/plugin.json
Thanks for pointing me to this branch!
> Remove invalid comma from JSON structure

- plugins/datasource-zabbix/zabbixAPIWrapper.js
- plugins/panel-triggers/editor.html
- plugins/panel-triggers/module.js
Added a option to select which events should be displayed, thus giving
the ability to have a trigger history, showing all the problem events as
well as the OK events.
> Add select events option

- README.md
Dockerized Grafana with Zabbix plugin provides easy deployment for Docker users.
> README info about Dockerized Grafana with Zabbix plugin

- zabbix/datasource.js
- zabbix/partials/annotations.editor.html
The annotation option code is a bit crude.
> Annotation update for 2.5.1 and annotation option to show the Zabbix hostname

- docs/sources/reference/functions.md
Hi, I found & fixed typo of docs for functions `timeShift`.
Thank you so nice plugin 👍
> Fixed docs for functions "timeShift"

- docs/sources/installation/index.md
> small documentation fix

- src/datasource-zabbix/dataProcessor.js
- src/datasource-zabbix/metricFunctions.js
- src/datasource-zabbix/query.controller.js
- src/datasource-zabbix/responseHandler.js
Sum and count aggregations of metrics (I really need this)
Signed-off-by: Ruslan Semov <me@recluse.ru> # @
> Sum and count aggregations added

- src/datasource-zabbix/DataProcessor.js
- src/datasource-zabbix/metricFunctions.js
hi, due to a need for the company where I work, I created a new percentile function in your project, the purpose of it is to make a kind of median, only instead of always taking the middle value (50%), it will take any position that is passed (n%). In my language is called "percentil" I do not know if in English is how it is written. It would be interesting for us the project stay synchronized with yours development, in order to use your future updates.
> new function percentil

- src/datasource-zabbix/dataProcessor.js
- src/datasource-zabbix/metricFunctions.js
- src/datasource-zabbix/specs/timeseries.spec.js
- src/datasource-zabbix/timeseries.js
Will resolve #637.
Adding a shift function.
> Offset function added

- src/datasource-zabbix/datasource.js
- src/datasource-zabbix/partials/query.editor.html
- src/datasource-zabbix/responseHandler.js
- src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.js
PR related: #728 
Added support to show IT Services graph over time and to apply "Functions" on it. 
* Interval between each SLA range: 86400s (1d);
* When the time range is less than 1d it will return the exactly range specified;
> Feature 728 sla graph over time

- .circleci/deploy-docs.sh
- .circleci/make-release.sh
Hi @alexanderzobnin,
This is a trivial fix for the `.circleci/*.sh*` shell scripts for the issues detected by [shellcheck](https://github.com/koalaman/shellcheck).
> .circleci/*.sh: Fix shellcheck issues

- pkg/zabbix_api.go
issue https://github.com/alexanderzobnin/grafana-zabbix/issues/799
Added logic to renew the auth token if expired and the default number of attempts allowed is set to 3.
> Backend: Added logic to renew auth token if expired

- pkg/zabbix_api.go
Related to #800 
Not sure if Grafana handles all of the datasource configuration, or some part of the frontend needs to be updated to save to the secure data. Also can't currently test this change in Grafana.
Since the change was pretty simple, I made some additional changes to appease golint and cleaned up redundant code that was being used, presumably, for debug logging.
> Backend: Check secure JSON data for password before plaintext JSON data

- src/datasource-zabbix/zabbix/connectors/zabbix_api/zabbixAPIConnector.js
Removing the console logging and returning the result.
> Backend: Handle response on the frontend

- docs/sources/installation/index.md
A few minor improvements.
Does a documentation change still need an issue created first?
> Installation Instructions spelling and grammar fixes

- src/datasource-zabbix/zabbix/connectors/sql/mysql.js
- src/datasource-zabbix/zabbix/connectors/sql/sqlConnector.js
Fix for issue https://github.com/alexanderzobnin/grafana-zabbix/issues/752
> Fix to consolidate avg accuracy

- .circleci/config.yml
- .circleci/github/publishRelease.js
- .circleci/make-release.sh
- .gitignore
- package.json
- yarn.lock
This PR closes #1038. Added signing plugin step.
> CI: sign plugin during release

- src/panel-triggers/ProblemsPanel.tsx
- src/panel-triggers/components/AlertList/AlertCard.tsx
- src/panel-triggers/components/Problems/ProblemDetails.tsx
- src/panel-triggers/components/Problems/Problems.tsx
- src/panel-triggers/module.tsx
- src/panel-triggers/types.ts
This PR adds option which allows formatting problem description as HTML.
Fixes #1557
> Problems: Allow HTML in description

- .github/workflows/lint.yml
This GitHub action is going to run `yarn lint` on every push.
> Chore: Run yarn lint in CI

- .gitignore
> Chore: Update gitignore

- package.json
- src/datasource/components/ConfigEditor.tsx
- src/datasource/components/Divider.tsx
- yarn.lock
- update the config page to match the best practices doc.
- add @grafana/experimental package, components needed for best practices
- custom Divider component to ensure backwards compatibility.
> Update config page to follow best practices

- src/datasource/components/QueryEditor.tsx
- src/datasource/components/QueryEditor/QueryEditorRow.tsx
- src/datasource/components/VariableQueryEditor.tsx
- src/datasource/components/ZabbixInput.tsx
- src/panel-triggers/components/AckModal.tsx
- src/panel-triggers/components/ExecScriptModal.tsx
aims to remove all legacy forms and replaces them with updated components
> legacy form migration

- CHANGELOG.md
- package.json
release version 4.4.4 of the zabbix datasource.
> release version 4.4.4

- CHANGELOG.md
a fix was not added to the changelog for 4.4.5
> add missing changelog entry for 4.4.5

- src/datasource/components/ConfigEditor.tsx
Forgot to fix it for API token reset in https://github.com/grafana/grafana-zabbix/pull/1750
Fixes #1796
> Fix: API token reset not working

- CHANGELOG.md
- package.json
- pkg/zabbix/methods.go
- pkg/zabbixapi/migration.go
- pkg/zabbixapi/zabbix_api.go
- src/datasource/zabbix/connectors/zabbix_api/zabbixAPIConnector.ts
- src/datasource/zabbix/types.ts
Fixes https://github.com/grafana/grafana-zabbix/issues/1935
> plugin version 4.6.0 compatiblity issues

- package.json
- playwright.config.ts
- tests/e2e/smoke.test.ts
- yarn.lock
creates a smoke test for the zabbix data source
closes https://github.com/grafana/data-sources/issues/194
> Add E2E smoke test

- src/datasource/components/ConfigEditor.tsx
* Link the PR to the related issue
https://github.com/grafana/grafana-zabbix/issues/2067
> Set correct link to the documentation

- src/datasource/components/QueryEditor/QueryFunctionsEditor.tsx
Resolves #2042
Fixed a bug that caused strange behaviour when adding multiple replaceAlias functions
> Fix: [#2042] replaceAlias function ordering in the query editor causing buggy ui interactions

- .changeset/nasty-baboons-listen.md
- src/datasource/dataProcessor.ts
- src/datasource/datasource.ts
- src/datasource/specs/dataProcessor.spec.ts
> Fix: alias functions in Services query type
